- hosts: localhost

  tasks:
    - name: Developer Tools related tasks
      ansible.builtin.include_tasks:
        file: tasks/developer-tools.yml

    - name: Desktop Tools related tasks
      ansible.builtin.include_tasks:
        file: tasks/desktop-tools.yml

