---
- name: Install asdf
  community.general.homebrew:
    name: asdf
    state: present
  tags:
    - developer-tools
    - install
    - asdf
    - version-manager

- name: Install minikube
  community.general.homebrew:
    name: minikube
    state: present
  tags:
    - developer-tools
    - install
    - minikube
    - kubernetes

- name: Install asdf plugins and software
  shell: ./bin/asdf/asdf install
  tags:
    - developer-tools
    - install
    - asdf
    - asdf-plugins
    - asdf-software
